
version: '3'

services:
  database:
    container_name: psql_db
    image: postgres:latest
#    restart: always
    environment:
      POSTGRES_DB : shoprix
      POSTGRES_PASSWORD: pramee-12345
      POSTGRES_USER: postgres
      DATABASE_HOST: psql_db

#    networks:
#      - api-network
#      PGPORT: 5432
    ports:
      - 5432:5432
    volumes:
      - .././data:/var/lib/postgresql/data

  web:
    container_name: api
    build: .
#    networks:
#      - api-network
    ports:
      - 8000:8000
    restart: on-failure
    environment:
        - WAIT_HOSTS=database:5432
    depends_on:
      - database
    volumes:
      - .././data:/usr/local/app
    command: sh -c "./main"