apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-database
  labels:
    app: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec: 
     containers:
        - name: postgres
          image: postgres:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5432
          env:
           - name: POSTGRES_DB
             valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-db 
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: psql-secret
                 key: psql-user

           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: psql-secret
                 key: psql-password
           - name: POSTGRES_HOST
             value: psql-db
           - name: POSTGRES_DATABASE
             valueFrom:
               secretKeyRef:
                 name: psql-secret
                 key: psql-db      
---
apiVersion: v1
kind: Service
metadata:
  name: psql-db
spec:
  selector:
    app: psql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432