apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: prameeshp/shoprix:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: dbHost
            value: psql-db
          - name: dbPort
            value: '5432'
          - name: dbUser
            value: postgres
          - name: dbPassword
            value: pramee-12345
          - name: dbName
            value: shoprix
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: psql-config
                key: psql-url

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 8000
    targetPort: 8000